# Generated by Django 6.0 on 2025-12-19 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscalationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "steps",
                    models.JSONField(
                        help_text="List of escalation steps with timing and recipients"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="notificatio_name_baf000_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("project", "Project"), ("task", "Task")],
                        max_length=16,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("near_deadline", "Near Deadline"),
                            ("predicted_delay", "Predicted Delay"),
                            ("stale_progress", "Stale Progress"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Meaning depends on trigger (hours or probability)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("channels", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "escalation_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notification.escalationpolicy",
                    ),
                ),
                (
                    "target_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
                (
                    "target_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_type", models.CharField(max_length=16)),
                (
                    "generated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("channel", models.CharField(max_length=64)),
                ("content", models.TextField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("response", models.JSONField(blank=True, default=dict)),
                (
                    "target_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
                (
                    "target_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="task.task",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="notification.notificationrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notificationrule",
            index=models.Index(
                fields=["target_type"], name="notificatio_target__fc37d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationrule",
            index=models.Index(
                fields=["trigger_type"], name="notificatio_trigger_25f8e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["rule"], name="notificatio_rule_id_1d7093_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["generated_at"], name="notificatio_generat_0f23e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["status"], name="notificatio_status_71d9cf_idx"),
        ),
    ]
