# Generated by Django 6.0 on 2025-12-19 17:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(db_index=True, max_length=32)),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_finish", models.DateField(blank=True, null=True)),
                (
                    "health_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cached 0-100 health metric",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("is_mandatory", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_type", models.CharField(max_length=32)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("summary", models.TextField(blank=True)),
                ("payload", models.JSONField()),
                (
                    "export_ref",
                    models.CharField(
                        blank=True,
                        help_text="Optional file reference/path",
                        max_length=512,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimelineSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("network_json", models.JSONField()),
                ("gantt_json", models.JSONField()),
                ("summary", models.JSONField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_snapshots",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["status"], name="project_pro_status_d7ebb2_idx"),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["owner"], name="project_pro_owner_i_5d20d9_idx"),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["project"], name="project_mil_project_400fb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["due_date"], name="project_mil_due_dat_485730_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectreport",
            index=models.Index(
                fields=["project"], name="project_pro_project_75c30c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectreport",
            index=models.Index(
                fields=["report_type"], name="project_pro_report__a9ead8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectreport",
            index=models.Index(
                fields=["created_at"], name="project_pro_created_7f281f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelinesnapshot",
            index=models.Index(
                fields=["project", "created_at"], name="project_tim_project_908ae9_idx"
            ),
        ),
    ]
