# Generated by Django 6.0 on 2025-12-16 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "capacity_hours_per_week",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("team", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResourceAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_time", models.DateTimeField(auto_now_add=True)),
                (
                    "committed_hours",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "available_hours",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("calendar_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="resource.resource",
                    ),
                ),
            ],
        ),
    ]
