# Generated by Django 6.0 on 2025-12-19 17:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                (
                    "capacity_hours_per_week",
                    models.DecimalField(decimal_places=2, default=40.0, max_digits=6),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("team", models.CharField(blank=True, max_length=128)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResourceAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_time",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "committed_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "available_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("calendar_metadata", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_snapshots",
                        to="resource.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_time"],
            },
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["email"], name="resource_re_email_fcdcb1_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["is_active"], name="resource_re_is_acti_9dd2f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourceavailability",
            index=models.Index(
                fields=["resource", "snapshot_time"],
                name="resource_re_resourc_be262f_idx",
            ),
        ),
    ]
