# Generated by Django 6.0 on 2025-12-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resource", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="skill_skill_name_fbf128_idx"),
                    models.Index(
                        fields=["category"], name="skill_skill_categor_405f6b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ResourceSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proficiency_level",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Optional 1-5 proficiency level",
                        null=True,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_skills",
                        to="resource.resource",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_skills",
                        to="skill.skill",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["resource", "skill"],
                        name="skill_resou_resourc_95ea86_idx",
                    )
                ],
                "unique_together": {("resource", "skill")},
            },
        ),
    ]
