# Generated by Django 6.0 on 2025-12-19 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
        ("resource", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To Do"),
                            ("in_progress", "In Progress"),
                            ("blocked", "Blocked"),
                            ("review", "In Review"),
                            ("done", "Done"),
                        ],
                        db_index=True,
                        default="todo",
                        max_length=32,
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Business importance weight"
                    ),
                ),
                ("planned_start", models.DateTimeField(blank=True, null=True)),
                ("planned_finish", models.DateTimeField(blank=True, null=True)),
                (
                    "optimistic_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "most_likely_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "pessimistic_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "expected_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "is_on_critical_path",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "total_float_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "allocated_effort",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "locked",
                    models.BooleanField(
                        default=False, help_text="When true, do not auto-reassign"
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="resource.resource",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="task.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskAssignmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("action", models.CharField(max_length=32)),
                ("actor", models.CharField(blank=True, max_length=128)),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="resource.resource",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="task.task"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("task_task", "Task->Task"),
                            ("resource_task", "Resource->Task"),
                        ],
                        max_length=24,
                    ),
                ),
                ("predecessor_team", models.CharField(blank=True, max_length=128)),
                (
                    "lag_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "dependent_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="task.task",
                    ),
                ),
                (
                    "predecessor_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resource.resource",
                    ),
                ),
                (
                    "predecessor_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependents",
                        to="task.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("model_name", models.CharField(max_length=128)),
                (
                    "probability_of_delay",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="task.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "snapshot_time",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "percent_complete",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "effort_consumed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("status_note", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_snapshots",
                        to="task.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_time"],
            },
        ),
        migrations.CreateModel(
            name="TaskReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_type", models.CharField(max_length=32)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                ("summary", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="task.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "status"], name="task_task_project_31b811_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["is_on_critical_path", "status"],
                name="task_task_is_on_c_565db8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["project", "updated_at"], name="task_task_project_d41541_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(
                fields=["resource", "start_date"], name="task_taskas_resourc_d5813c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskassignment",
            index=models.Index(fields=["task"], name="task_taskas_task_id_be6dbe_idx"),
        ),
        migrations.AddIndex(
            model_name="taskassignmenthistory",
            index=models.Index(
                fields=["task", "timestamp"], name="task_taskas_task_id_0ff132_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskdependency",
            index=models.Index(
                fields=["dependent_task"], name="task_taskde_depende_9d0797_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskdependency",
            index=models.Index(
                fields=["dependency_type"], name="task_taskde_depende_62c3c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskprediction",
            index=models.Index(
                fields=["task", "generated_at"], name="task_taskpr_task_id_d7e609_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskprogress",
            index=models.Index(
                fields=["task", "snapshot_time"], name="task_taskpr_task_id_633262_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskreport",
            index=models.Index(
                fields=["task", "report_type"], name="task_taskre_task_id_33aa05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskreport",
            index=models.Index(
                fields=["created_at"], name="task_taskre_created_8441df_idx"
            ),
        ),
    ]
